# +--------------------------------------+
# | BLE Inverter Proxy - CAN Example     |
# +--------------------------------------+
# Node B: BLE Client → CAN output
# Connects to YamBMS BLE server and outputs to inverter via CAN
#
# This is a standalone ESP32 that receives battery data from your
# YamBMS server via BLE and sends it to the inverter over CAN bus.

esphome:
  name: inverter-proxy-can
  friendly_name: "Inverter Proxy CAN"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# +--------------------------------------+
# | Proxy Configuration                  |
# +--------------------------------------+
substitutions:
  proxy_id: 'inv_proxy'
  proxy_name: 'Inverter Proxy'
  canbus_node_id: 'canbus_proxy'

  # BLE Server MAC address (Node A)
  # Get this from Node A logs after first boot
  # Format: XX:XX:XX:XX:XX:XX
  yambms_server_mac: 'AA:BB:CC:DD:EE:FF'  # <- Change this!

# +--------------------------------------+
# | CAN bus hardware                     |
# +--------------------------------------+
# ESP32 built-in CAN (TWAI) controller
# Adjust TX/RX pins to match your wiring
canbus:
  - platform: esp32_can
    id: canbus_proxy
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 1
    bit_rate: 500kbps

# +--------------------------------------+
# | BLE Client + CAN Output packages     |
# +--------------------------------------+
packages:
  # BLE Client - connect to YamBMS server
  ble_client:
    url: https://github.com/RAR/esphome-yambms
    ref: ble-inverter-proxy
    refresh: 0s
    files:
      - path: 'packages/inverter/inverter_proxy_ble_client.yaml'

  # CAN output to inverter
  can_output:
    url: https://github.com/RAR/esphome-yambms
    ref: ble-inverter-proxy
    refresh: 0s
    files:
      - path: 'packages/inverter/inverter_proxy_canbus.yaml'

# +--------------------------------------+
# | Protocol Selection                   |
# +--------------------------------------+
# Available protocols:
#   "Disabled", "PYLON 1.2", "PYLON V2", "SMA", "Victron", "LuxPower"
# Default: "PYLON V2"
# Override here if needed:
#
# select:
#   - id: !extend inv_proxy_protocol
#     initial_option: "PYLON 1.2"

# +--------------------------------------+
# | Setup Instructions                   |
# +--------------------------------------+
# 1. Flash Node A (YamBMS Server) first
#    - Include yambms_ble_server.yaml in your YamBMS config
# 2. Check Node A logs for BLE MAC address
# 3. Update yambms_server_mac above with Node A's MAC
# 4. Adjust CAN TX/RX pins for your board
# 5. Flash this Node B
# 6. Node B will auto-connect to Node A via BLE
# 7. Connect CAN bus to inverter
#    - Add 120Ω termination resistor if needed
# 8. Monitor logs for connection status
