# +--------------------------------------+
# | BLE Charger Proxy - RS485 Example    |
# +--------------------------------------+
# Node B: BLE Client → RS485 Pylontech output
# Connects to YamBMS BLE server and responds to charger RS485
# queries with full Pylontech protocol (0x60-0x63).
#
# Tested with: Ecoworthy EC100 48V 100A charger
# Board: Waveshare ESP32-S3-RS485-CAN
#
# See CHARGER_PROXY_README.md for full documentation.

esphome:
  name: charger-proxy
  friendly_name: "Charger Proxy"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:
  level: INFO
  hardware_uart: USB_SERIAL_JTAG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# +--------------------------------------+
# | Proxy Configuration                  |
# +--------------------------------------+
substitutions:
  proxy_id: 'ew_proxy'
  # BLE Server MAC address (Node A / YamBMS)
  # Get this from Node A logs after first boot
  # Format: XX:XX:XX:XX:XX:XX
  yambms_server_mac: 'AA:BB:CC:DD:EE:FF'  # <- Change this!

# +--------------------------------------+
# | BLE Client + Charger RS485 packages  |
# +--------------------------------------+
packages:
  # BLE Client - connects to YamBMS BLE server
  ble_client:
    url: https://github.com/RAR/esphome-yambms-addons
    ref: main
    refresh: 0s
    files:
      - path: 'packages/inverter/inverter_proxy_ble_client.yaml'

  # Charger A - RS485 Pylontech output (Waveshare onboard RS485)
  charger_a:
    url: https://github.com/RAR/esphome-yambms-addons
    ref: main
    refresh: 0s
    files:
      - path: 'packages/charger/charger_proxy_rs485.yaml'
        vars:
          charger_id: 'charger_a'
          charger_name: 'Charger A'
          charger_uart_id: 'uart_charger_a'
          charger_tx_pin: '17'
          charger_rx_pin: '18'
          charger_flow_control_pin: '21'

  # Charger B - second RS485 adapter (uncomment to enable)
  # charger_b:
  #   url: https://github.com/RAR/esphome-yambms-addons
  #   ref: main
  #   refresh: 0s
  #   files:
  #     - path: 'packages/charger/charger_proxy_rs485.yaml'
  #       vars:
  #         charger_id: 'charger_b'
  #         charger_name: 'Charger B'
  #         charger_uart_id: 'uart_charger_b'
  #         charger_tx_pin: '5'
  #         charger_rx_pin: '6'
  #         charger_flow_control_pin: '7'

# +--------------------------------------+
# | Setup Instructions                   |
# +--------------------------------------+
# 1. Flash Node A (YamBMS Server) first
#    - Include yambms_ble_server.yaml in your YamBMS config
# 2. Check Node A logs for BLE MAC address
# 3. Update yambms_server_mac above with Node A's MAC
# 4. Flash this Node B (Waveshare ESP32-S3-RS485-CAN)
# 5. Node B will auto-connect to Node A via BLE
# 6. Connect RS485 A+/B- to charger's RJ45 battery port
#    - RJ45 pins 2,7 = A+  |  pins 1,8 = B-
# 7. Power on charger — should see Pylon queries in logs
# 8. Charger display should show SOC
# 9. Toggle "Charge Enable" switch in HA to control charging
