# Updated : 2026.02.02
# Version : 1.0.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# +--------------------------------------+
# | BLE Server for EG4 LL V2 RS485 BMS   |
# +--------------------------------------+
# This package reads EG4 LL V2 BMS data via RS485 Modbus and exposes
# it to remote clients via BLE GATT server.
#
# Required substitutions:
#   bms_id: The BMS ID number
#   bms_name: Display name for the BMS
#   bms_modbus_address: Modbus address of the BMS (usually 1)
#   modbus_controller_id: The modbus controller ID

substitutions:
  bms_model: "EG4 LLV2"
  bms_protocol: "Multi-node BLE"

packages:
  bms_sensors: !include bms_sensors_EG4_LLV2_RS485_bms_full.yaml
  bms_ble_server: !include bms_ble_server.yaml
